/**
 * COLOUR TEMPLATES: a whole palette in one press.
 *
 * Operator: "add a few colour templates at the top of the appearance settings,
 * learn from some VS Code themes."
 *
 * ## What a template is, and why it is not a list of colours somebody liked
 *
 * A TEMPLATE IS A HUE AND A CHROMA APPLIED TO VAM'S OWN LIGHTNESS LADDER. Each
 * surface keeps the exact L* the stylesheet gives it and moves only in a* and
 * b*. That single rule is what makes offering presets safe at all:
 *
 *   - THE ELEVATION ORDER SURVIVES. `styles.css` orders its surfaces
 *     ground < sunken < well < header < panel < sidebar/pane < raised < card
 *     and a release was spent on that order being visible rather than merely
 *     recorded. A preset that chose its own lightnesses would undo it in one
 *     click, and the operator -- who asked twice for a lighter, less flat dark
 *     theme -- would get the flat one back under a nicer name.
 *   - THE JND SEPARATIONS SURVIVE. `pane -> card` (3.30 L*) and
 *     `pane -> raised` (2.36 L*) are the two the operator's "too dark" reports
 *     turned out to be about. They are properties of the ladder, so every
 *     template inherits them.
 *   - THE CONTRAST FLOORS VERY NEARLY SURVIVE, and "very nearly" is why
 *     `test/prefs/palette-templates.test.ts` exists. Adding chroma moves
 *     relative luminance a little even at a fixed L*, so each template's worst
 *     ink pair was measured rather than assumed. The worst across all four, in
 *     both themes, is 4.567:1 against WCAG 1.4.3's 4.5.
 *
 * ## The seven tokens a template sets, and the six it must not
 *
 * It sets the ROOM: `panel`, `sidebar`, `pane`, `raised`, `card`, the In
 * bubble, and `ink`.
 *
 * It never sets the SIGNALS: `running`, `waiting`, `cursor-ring`, `idle`,
 * `done` and `failed`. Those are not decoration -- `styles.css` argues each
 * one where it defines it, and amber in this app means exactly one thing, "a
 * session is blocked on your answer". A preset that recoloured the status row
 * would be changing what an operator reads to decide what to do next, which is
 * not what "a colour template" asks for. They stay at the stylesheet's values
 * and every template's surfaces are measured against them.
 *
 * ## Learned from, not copied from
 *
 * Each entry records the VS Code theme its character was read off. The VALUES
 * are vam's own and could not be otherwise: those themes are built on their
 * own lightness ladders and their own text colours, and dropping their hexes
 * in here would fail this palette's contrast floors on inks they never had to
 * carry. `studied` is on the record so the next person can see what was
 * looked at without mistaking it for what was taken.
 *
 * ## What a template does NOT do
 *
 * It writes into the theme ON SCREEN and leaves the other one alone, exactly
 * as `clearPalette` does and for the same reason: the other theme's colours
 * were chosen on a screen this one cannot see. Applying one is an ordinary
 * palette override -- every swatch still shows it, every per-token reset still
 * clears it, and `reset <theme> colours` still puts the whole thing back.
 * There is no "current template" stored anywhere, deliberately: the operator
 * can move one swatch afterwards, and a remembered name would then be a label
 * for a palette that is no longer that template.
 */

import type { EffectiveTheme, PaletteOverrides, Prefs } from './prefs.js';
import { PALETTE_TOKENS, setPaletteColor } from './prefs.js';

/** The id of a shipped template. */
export type PaletteTemplateId = 'slate' | 'nordic' | 'ember' | 'plum';

export interface PaletteTemplate {
  readonly id: PaletteTemplateId;
  /** What the button says. Lower case, like every other label in Settings. */
  readonly label: string;
  /** One line under the row, for the template under the pointer. */
  readonly hint: string;
  /** The VS Code theme whose character this was read off. Never its values. */
  readonly studied: string;
  readonly dark: PaletteOverrides;
  readonly light: PaletteOverrides;
}

/**
 * The four, each generated by putting its hue and chroma on the ladder above
 * and then measured. The dark chroma is in brackets: past about 10 the
 * surfaces stop reading as "a grey with a cast" and start reading as coloured
 * panels, which is a different product.
 */
export const PALETTE_TEMPLATES: readonly PaletteTemplate[] = [
  {
    id: 'slate',
    label: 'slate',
    hint: 'a cool blue-grey room — the quietest of the four',
    studied: 'GitHub Dark Dimmed, One Dark Pro',
    // hue 255°, chroma 5 (dark) / 2.5 (light).
    dark: {
      '--vam-panel': '#1e252b',
      '--vam-sidebar': '#21282e',
      '--vam-pane': '#21282e',
      '--vam-raised': '#262d33',
      '--vam-card': '#282f35',
      '--vam-in-bubble': '#3a444d',
      '--vam-ink': '#ebedf0',
    },
    light: {
      '--vam-panel': '#fbffff',
      '--vam-sidebar': '#ebeff3',
      '--vam-pane': '#ebeff3',
      '--vam-raised': '#ecf0f4',
      '--vam-card': '#fbffff',
      '--vam-in-bubble': '#fffaf4',
      '--vam-ink': '#17181a',
    },
  },
  {
    id: 'nordic',
    label: 'nordic',
    hint: 'the same blue, taken further — cold and low-contrast',
    studied: 'Nord',
    // hue 260°, chroma 9 (dark) / 4 (light).
    dark: {
      '--vam-panel': '#192530',
      '--vam-sidebar': '#1c2833',
      '--vam-pane': '#1c2833',
      '--vam-raised': '#212d39',
      '--vam-card': '#232f3b',
      '--vam-in-bubble': '#3b444d',
      '--vam-ink': '#ebedf0',
    },
    light: {
      '--vam-panel': '#faffff',
      '--vam-sidebar': '#e9eff6',
      '--vam-pane': '#e9eff6',
      '--vam-raised': '#ebf1f7',
      '--vam-card': '#faffff',
      '--vam-in-bubble': '#fdf9f4',
      '--vam-ink': '#17181a',
    },
  },
  {
    id: 'ember',
    label: 'ember',
    hint: 'warm brown-grey, for a screen that is on after dark',
    studied: 'Monokai, Solarized Dark',
    // hue 65°, chroma 6 (dark) / 3 (light).
    dark: {
      '--vam-panel': '#2a231d',
      '--vam-sidebar': '#2e261f',
      '--vam-pane': '#2e261f',
      '--vam-raised': '#332b24',
      '--vam-card': '#352d26',
      '--vam-in-bubble': '#4b4139',
      '--vam-ink': '#efedea',
    },
    light: {
      '--vam-panel': '#fffefa',
      '--vam-sidebar': '#f3ede9',
      '--vam-pane': '#f3ede9',
      '--vam-raised': '#f5efeb',
      '--vam-card': '#fffefa',
      '--vam-in-bubble': '#f4faff',
      '--vam-ink': '#1a1816',
    },
  },
  {
    id: 'plum',
    label: 'plum',
    hint: 'a violet cast, the warmest of the cool three',
    studied: 'Dracula, Tokyo Night',
    // hue 320°, chroma 6 (dark) / 3 (light).
    dark: {
      '--vam-panel': '#282229',
      '--vam-sidebar': '#2b252c',
      '--vam-pane': '#2b252c',
      '--vam-raised': '#302a32',
      '--vam-card': '#322c34',
      '--vam-in-bubble': '#48404a',
      '--vam-ink': '#eeecef',
    },
    light: {
      '--vam-panel': '#fffeff',
      '--vam-sidebar': '#f1edf2',
      '--vam-pane': '#f1edf2',
      '--vam-raised': '#f3eff4',
      '--vam-card': '#fffeff',
      '--vam-in-bubble': '#f8fcf7',
      '--vam-ink': '#19181a',
    },
  },
];

/**
 * THE LIGHT BUBBLE IS THE ONE VALUE NOT ON THE TEMPLATE'S OWN HUE, and the
 * reason is worth keeping next to the table.
 *
 * vam's light In bubble clears its ΔE floor by differing from a WARM pane in
 * HUE -- that theme's pane sits at 86% relative luminance, so nothing lighter
 * than it can buy distance with lightness. A template that tints the pane
 * towards the bubble's own hue takes that away, and the bubble stops being
 * drawn: the exact complaint, reported twice, that created the token. So each
 * template's light bubble is rotated off its pane and then solved against the
 * floor, which is why `ember` (warm) has a cool bubble and `slate` (cool) has
 * a warm one.
 */

const BY_ID = new Map(PALETTE_TEMPLATES.map((t) => [t.id, t]));

/** The overrides one template writes in one theme, or `{}` for an unknown id. */
export function templatePalette(id: PaletteTemplateId, theme: EffectiveTheme): PaletteOverrides {
  const template = BY_ID.get(id);
  return template === undefined ? {} : template[theme];
}

/**
 * Apply a template to the theme on screen.
 *
 * REPLACES, rather than merging: two presets half-applied over each other is a
 * palette nobody designed and nobody measured. Every offered token is cleared
 * first, so a template that does not set `running` leaves `running` at the
 * stylesheet's value even if the operator had picked one by hand -- which is
 * what "apply this template" means, and is undone by `reset <theme> colours`
 * the same as any other palette state.
 *
 * An id this file does not know changes NOTHING and returns the same object, so
 * a caller with a stale id cannot blank somebody's palette. Every value still
 * goes through `setPaletteColor`, which drops tokens vam does not offer -- the
 * table above is checked against `PALETTE_TOKENS` by the test, but the runtime
 * does not take that on trust either.
 */
export function applyPaletteTemplate(
  prefs: Prefs,
  theme: EffectiveTheme,
  id: PaletteTemplateId,
): Prefs {
  const template = BY_ID.get(id);
  if (template === undefined) {
    return prefs;
  }
  const values = template[theme];
  let next: Prefs = { ...prefs, palette: { ...prefs.palette, [theme]: {} } };
  for (const { token } of PALETTE_TOKENS) {
    const value = values[token];
    if (value !== undefined) {
      next = setPaletteColor(next, theme, token, value);
    }
  }
  return next;
}
