/**
 * macOS installer: unzip the verified download, then let a detached `/bin/sh`
 * script swap the bundle after this process has exited.
 *
 * No signing, so no Squirrel.Mac: the swap is ours. The script is generated by
 * a pure function (`macInstallScript`) so its quoting and its rollback can be
 * tested by actually running it against fake bundles.
 */

import { execFile as nodeExecFile, type SpawnOptions, spawn } from 'node:child_process';
import { accessSync, constants } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { UpdateErrorCode } from '../../shared/update.js';

export type InstallFailure = { readonly code: UpdateErrorCode; readonly message: string };

const MOVE_MESSAGE = 'Move vam to /Applications and try again';
/** The bundle name inside the release zip (productName + .app). */
const NEW_BUNDLE = 'vam.app';

const BUNDLE_RE = /^(.+\.app)\/Contents\/MacOS\/[^/]+$/;

/** `/Applications/vam.app` from the running executable, or null outside a bundle. */
export function appBundleFromExecPath(execPath: string): string | null {
  const m = BUNDLE_RE.exec(execPath);
  return m === null ? null : (m[1] as string);
}

export function defaultIsWritable(dir: string): boolean {
  try {
    accessSync(dir, constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Why this install cannot be swapped in place, or null. The swap renames the
 * bundle inside its parent directory, so that directory is what must be
 * writable. Checked BEFORE downloading 100 MB that could never be installed.
 */
export function macInstallBlocker(
  appPath: string,
  deps: { readonly isWritable: (dir: string) => boolean },
): InstallFailure | null {
  // A quarantined app run from Downloads executes from a randomised read-only
  // mount; replacing that path replaces nothing the user launches.
  if (appPath.includes('/AppTranslocation/')) {
    return { code: 'translocated', message: MOVE_MESSAGE };
  }
  if (deps.isWritable(dirname(appPath))) return null;
  if (appPath.startsWith('/Volumes/')) return { code: 'read-only', message: MOVE_MESSAGE };
  return { code: 'not-writable', message: MOVE_MESSAGE };
}

/** POSIX single-quoting: safe for any byte but NUL. */
export function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export type MacScriptInput = {
  /** The running app's pid: the script waits for it to be gone. */
  readonly pid: number;
  readonly appPath: string;
  readonly newAppPath: string;
  readonly stagingDir: string;
  readonly backupPath: string;
  readonly logPath: string;
  /** Give up (touching nothing) if the app is still alive after this long. */
  readonly waitSeconds?: number;
  /** Command paths; absolute by default so PATH cannot redirect them. */
  readonly commands?: {
    readonly open: string;
    readonly xattr: string;
    readonly pgrep?: string;
  };
};

/**
 * The swap, as `/bin/sh` text:
 *  1. wait for the pid to exit (timeout -> abort, nothing touched), then make
 *     sure nothing still runs from the bundle (abort, nothing touched);
 *  2. move the old app aside (fails -> nothing changed, relaunch old);
 *  3. move the new app in (fails -> remove the partial, restore old, relaunch old;
 *     if the restore fails too, say where the old app is and open nothing);
 *  4. clear quarantine attributes, delete backup and staging, open the new app.
 */
export function macInstallScript(input: MacScriptInput): string {
  const q = shellQuote;
  const open = q(input.commands?.open ?? '/usr/bin/open');
  const xattr = q(input.commands?.xattr ?? '/usr/bin/xattr');
  const pgrep = q(input.commands?.pgrep ?? '/usr/bin/pgrep');
  const limit = Math.max(1, Math.round((input.waitSeconds ?? 120) * 2));
  return `#!/bin/sh
PID=${Number(input.pid)}
APP=${q(input.appPath)}
NEW=${q(input.newAppPath)}
STAGING=${q(input.stagingDir)}
BAK=${q(input.backupPath)}
LOG=${q(input.logPath)}
exec >>"$LOG" 2>&1
log() { echo "$(date '+%Y-%m-%dT%H:%M:%S') $*"; }
log "update: waiting for pid $PID"
i=0
while kill -0 "$PID" 2>/dev/null; do
  i=$((i + 1))
  if [ "$i" -ge ${limit} ]; then
    log "update: timed out waiting for the app to exit; nothing changed"
    exit 1
  fi
  sleep 0.5
done
# Escape the path for pgrep's regex.
PAT=$(printf '%s' "$APP/Contents/MacOS/" | sed 's#[][\\\\.*^$(){}?+|]#\\\\&#g')
if ${pgrep} -f "$PAT" >/dev/null 2>&1; then
  log "update: the app is still running from $APP; nothing changed"
  exit 1
fi
rm -rf "$BAK"
if ! mv "$APP" "$BAK"; then
  log "update: could not move the old app aside; nothing changed"
  ${open} "$APP"
  exit 1
fi
if ! mv "$NEW" "$APP"; then
  log "update: could not move the new app in; rolled back"
  if [ -e "$APP" ]; then
    rm -rf "$APP"
  fi
  if ! mv "$BAK" "$APP"; then
    log "update: restore failed; the previous app is at $BAK"
    exit 1
  fi
  ${open} "$APP"
  exit 1
fi
${xattr} -cr "$APP" || log "update: xattr failed (ignored)"
rm -rf "$BAK" "$STAGING"
log "update: installed; relaunching"
${open} "$APP"
`;
}

type ExecFile = (cmd: string, args: string[]) => Promise<{ stdout: string }>;

export type MacPrepareDeps = {
  readonly isWritable: (dir: string) => boolean;
  readonly exec: ExecFile;
  readonly rm: (path: string) => Promise<void>;
  readonly mkdir: (path: string) => Promise<void>;
  readonly writeFile: (path: string, text: string, mode: number) => Promise<void>;
};

export const realMacPrepareDeps: MacPrepareDeps = {
  isWritable: defaultIsWritable,
  exec: (cmd, args) =>
    new Promise((resolve, reject) => {
      nodeExecFile(cmd, args, { timeout: 120_000 }, (err, stdout) =>
        err ? reject(err) : resolve({ stdout: String(stdout) }),
      );
    }),
  rm: (p) => rm(p, { recursive: true, force: true }),
  mkdir: async (p) => {
    await mkdir(p, { recursive: true, mode: 0o700 });
  },
  writeFile: (p, text, mode) => writeFile(p, text, { mode }),
};

export type MacHandle = { readonly kind: 'mac-zip'; readonly scriptPath: string };
export type MacPrepareResult =
  | { readonly ok: true; readonly handle: MacHandle }
  | ({ readonly ok: false } & InstallFailure);

/**
 * Validate the install location, extract the zip into `staging-<version>/`,
 * confirm the bundle inside really is `version`, and write the swap script.
 * Nothing about the installed app changes here.
 */
export async function prepareMacInstall(
  input: {
    readonly version: string;
    readonly zipPath: string;
    readonly updatesDir: string;
    readonly execPath: string;
    readonly pid: number;
  },
  deps: MacPrepareDeps = realMacPrepareDeps,
): Promise<MacPrepareResult> {
  const appPath = appBundleFromExecPath(input.execPath);
  if (appPath === null) {
    return {
      ok: false,
      code: 'unsupported-install',
      message: 'vam is not running from an app bundle',
    };
  }
  const blocker = macInstallBlocker(appPath, deps);
  if (blocker !== null) return { ok: false, ...blocker };

  const stagingDir = join(input.updatesDir, `staging-${input.version}`);
  const newAppPath = join(stagingDir, NEW_BUNDLE);
  const fail = (message: string): MacPrepareResult => ({
    ok: false,
    code: 'install-failed',
    message,
  });
  try {
    await deps.rm(stagingDir);
    await deps.mkdir(stagingDir);
    // ditto (not unzip) is what preserves bundle symlinks, modes and xattrs.
    await deps.exec('/usr/bin/ditto', ['-x', '-k', input.zipPath, stagingDir]);
    const { stdout } = await deps.exec('/usr/bin/plutil', [
      '-extract',
      'CFBundleShortVersionString',
      'raw',
      '-o',
      '-',
      join(newAppPath, 'Contents', 'Info.plist'),
    ]);
    if (stdout.trim() !== input.version) {
      await deps.rm(stagingDir);
      return fail(`Downloaded app is version ${stdout.trim()}, expected ${input.version}`);
    }
    const scriptPath = join(input.updatesDir, `install-${input.version}.sh`);
    const script = macInstallScript({
      pid: input.pid,
      appPath,
      newAppPath,
      stagingDir,
      backupPath: `${appPath}.update-backup`,
      logPath: join(input.updatesDir, 'install.log'),
    });
    await deps.writeFile(scriptPath, script, 0o700);
    return { ok: true, handle: { kind: 'mac-zip', scriptPath } };
  } catch (e) {
    await deps.rm(stagingDir).catch(() => undefined);
    return fail(`Could not unpack the update: ${e instanceof Error ? e.message : String(e)}`);
  }
}

/** What a detached spawn hands back: enough to hear `spawn`/`error` and let go. */
export type SpawnedChild = {
  unref(): void;
  on(event: 'spawn' | 'error', listener: () => void): unknown;
};

export type Spawner = (cmd: string, args: readonly string[], opts: SpawnOptions) => SpawnedChild;

/** How long to wait for `spawn`/`error` before moving on. */
export const SPAWN_SETTLE_MS = 1000;

/**
 * Spawn detached and settle on `spawn`, `error` or a short timeout, never
 * hanging. The `error` listener stays attached (a spawn failure with none is an
 * uncaught exception in main during will-quit); a failure is swallowed, as
 * there is nothing left to do at will-quit but quit.
 */
export function spawnDetached(
  spawner: Spawner,
  cmd: string,
  args: readonly string[],
  opts: SpawnOptions,
  settleMs: number = SPAWN_SETTLE_MS,
): Promise<void> {
  return new Promise((resolve) => {
    const child = spawner(cmd, args, opts);
    const timer = setTimeout(resolve, settleMs);
    const done = (): void => {
      clearTimeout(timer);
      resolve();
    };
    child.on('spawn', done);
    child.on('error', done);
    child.unref();
  });
}

/** Start the swap script detached, so it outlives this process. Call at will-quit. */
export function launchMacInstall(
  handle: MacHandle,
  spawner: Spawner = spawn,
  settleMs?: number,
): Promise<void> {
  return spawnDetached(
    spawner,
    '/bin/sh',
    [handle.scriptPath],
    { detached: true, stdio: 'ignore' },
    settleMs,
  );
}
